# 系统配置
db_config:
  db_host = 'localhost'
  db_port = 3306
  db_user = 'root'
  db_password = 'lu020427'
  db_name = 'embybot'

bot_config:
  bot_token = 'xxx'
  bot_name = '@xxx'
  api_id = 99999999
  api_hash = "xxx"

emby_config:
  embyurl = 'xxx'
  embyapi = 'xxx'
  line = 'xxx'

tg_config:
  groupid = -100
  channelid = -100
  admin_list = []
  ban_channel_id = -100
