# 系统配置
# 注意为属性名:属性内容 格式
db_config:
  db_host : '107.150.58.242'
  db_port : 3306
  db_user : 'bot_db'
  db_password : '56fKJTdJWZeAnJxN'
  db_name : 'embybot'

bot_config:
  bot_token : '5773840462:AAEo_DQXhbOailgHVq9jFCUoIMh1_ZFZRko'
  bot_name : '@gfwEmby_bot'
  api_id : 17601473
  api_hash : "3d0afda852ace0a6b03e73908abfc849"

emby_config:
  embyurl : 'http://127.0.0.1:8096'
  embyapi : '2707f3ce2e41432cb6f54e64c5e0ae06'
  line : '''美国Kirino:http://us-s2.gfwemby.org
美国(原服务器):http://us-s1.gfwemby.org
美国AWS:http://aws-us.gfwemby.org
日本AWS:http://aws-jp.gfwemby.org
PORT ARE 80 OR 443
==============================
要想查看更多信息，请访问我们的wiki'''

tg_config:
  groupid : -1001887919023
  channelid : -1001741416803
  admin_list : [1659943903]
  ban_channel_id : -100